name: 'stadium_concessions_analytics'
version: '1.0.0'
config-version: 2

profile: 'stadium_concessions'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  stadium_concessions_analytics:
    +schema: raw
    +quote_columns: false

snapshots:
  stadium_concessions_analytics:
    +strategy: timestamp
    +updated_at: updated_at

models:
  stadium_concessions_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      core:
        +materialized: table
        +schema: marts
      finance:
        +materialized: table
        +schema: marts
    metrics:
      +materialized: view
      +schema: metrics

vars:
  dbt_date:date_spine:
    start_date: "2023-01-01"
    end_date: "2025-12-31"
